name: "Retype llms.txt Generator"
description: "Generates llms.txt from a Retype project"
author: "Zakaria Chahboun"
branding:
  icon: "file-text"
  color: "blue"

inputs:
  source:
    description: "Optional path to the Retype source markdowns directory (overrides input in retype.yml)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      shell: bash
      run: pip install pyyaml
    
    - name: Run llms.py
      shell: bash
      run: |
        if [ -n "${{ inputs.source }}" ]; then
          python "${{ github.action_path }}/llms.py" "${{ inputs.source }}"
        else
          python "${{ github.action_path }}/llms.py"
        fi
